version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
